# https://github.com/marketplace/actions/doxygen-action

name: Doxygen

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  doxygen:
    steps:
      runs-on: ubuntu-20.04
      - uses: mattnotmitt/doxygen-action@v1
        with:
          working-directory: 'submodule/'
          # doxyfile-path: './Doxyfile'
          doxyfile-path: 'docs/Doxygen'
