# https://github.com/marketplace/actions/doxygen-action

name: Doxygen

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  doxygen:
    uses: mattnotmitt/doxygen-action@v1
    with:
      working-directory: 'submodule/'
      # doxyfile-path: './Doxyfile'
      doxyfile-path: 'docs/Doxygen'
